services:
    isotope_product_licenses.listener.insert_tags:
        class: Oveleon\IsotopeProductLicenses\EventListener\InsertTagsListener
        arguments:
            - '@contao.framework'
        tags:
          - { name: contao.hook, hook: replaceInsertTags }
        public: true
